### ISSUE TITLE
"Invariant Failed" 

### ISSUE THREAD

**Issue by bullishtrader** [0xVentures/webapp#10]
This error is given when a members is trying to log in with a different address that is not whitelisted.

![unknown](https://user-images.githubusercontent.com/82927810/128386977-4bb5db64-3373-459d-ad82-961d3fd99a7e.png)

It would be better to change the message with "Invalid Address" or "This address is invalid"

**Comment by IShotTheSheriff** [comment]
![Zrzut ekranu 2021-08-6 o 16 29 37](https://user-images.githubusercontent.com/4144157/128525875-1d9ebde6-e22a-4539-9b48-e3c42e9750f7.png)

That's from last release.

**Comment by bullishtrader** [comment]
@IShotTheSheriff fantastic! marking this as DONE.
